# Generated by Django 5.1.7 on 2026-04-12 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliado', '0001_initial'),
        ('operador', '0001_initial'),
        ('tramite', '0002_alter_tramite_numero_tramite_and_more'),
        ('vehiculo', '0002_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=500)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaDeOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.CharField(choices=[('001', 'InterProvincial'), ('002', 'Interprov.ATL'), ('003', 'Interprov.Confederado'), ('004', 'Interprov.Confe.SCZ'), ('005', 'Interprov.Cooperativas')], max_length=3)),
                ('validez_periodo', models.CharField(choices=[('year', 'AÑO'), ('month', 'MES')], default='year', max_length=10)),
                ('validez_tiempo', models.PositiveIntegerField(default=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('valida_hasta', models.DateField(blank=True, null=True)),
                ('hora_recorrido', models.CharField(max_length=100)),
                ('viceversa', models.BooleanField(default=False)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas_de_operacion', to='afiliado.afiliado')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas_de_operacion', to='operador.operador')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarjeta_de_operacion.ruta')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_de_operacion', to='tramite.tramite')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas_de_operacion', to='vehiculo.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorridos', to='tarjeta_de_operacion.ruta')),
                ('tarjeta_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='tarjeta_de_operacion.tarjetadeoperacion')),
            ],
        ),
    ]
