# Generated by Django 5.1.7 on 2026-04-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliado', '0001_initial'),
        ('operador', '0001_initial'),
        ('tramite', '0001_initial'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaDeOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('p', 'PENDIENTE'), ('e', 'EMITIDA'), ('v', 'VENCIDA')], default='p', max_length=1)),
                ('ruta', models.TextField()),
                ('licencia', models.CharField(max_length=100)),
                ('validez', models.PositiveIntegerField(default=1)),
                ('monto', models.DecimalField(decimal_places=2, default=40.0, max_digits=8)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('valida_hasta', models.DateField(blank=True, null=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjeta_afiliado', to='afiliado.afiliado')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjeta_operador', to='operador.operador')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_tramite', to='tramite.tramite')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjeta_vehiculo', to='vehiculo.vehiculo')),
            ],
        ),
    ]
