# Generated by Django 5.1.7 on 2026-04-22 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarjeta_de_operacion', '0001_initial'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetadeoperacion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjeta_vehiculo', to='vehiculo.vehiculo'),
        ),
    ]
