# Generated by Django 5.1.7 on 2026-04-14 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarjeta_de_operacion', '0001_initial'),
        ('tramite', '0001_initial'),
        ('vehiculo', '0002_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetadeoperacion',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_de_operacion', to='tramite.tramite'),
        ),
        migrations.AddField(
            model_name='tarjetadeoperacion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas_de_operacion', to='vehiculo.vehiculo'),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='tarjeta_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='tarjeta_de_operacion.tarjetadeoperacion'),
        ),
    ]
