# Generated by Django 5.1.7 on 2026-04-15 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliado', '0001_initial'),
        ('operador', '0001_initial'),
        ('tarjeta_de_operacion', '0002_initial'),
        ('tramite', '0001_initial'),
        ('vehiculo', '0002_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetadeoperacion',
            name='afiliado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afiliados_tarjeta', to='afiliado.afiliado'),
        ),
        migrations.AlterField(
            model_name='tarjetadeoperacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tarjetadeoperacion',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operadores_tarjeta', to='operador.operador'),
        ),
        migrations.AlterField(
            model_name='tarjetadeoperacion',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_tarjeta', to='tarjeta_de_operacion.ruta'),
        ),
        migrations.AlterField(
            model_name='tarjetadeoperacion',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites_tarjeta', to='tramite.tramite'),
        ),
        migrations.AlterField(
            model_name='tarjetadeoperacion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_tarjeta', to='vehiculo.vehiculo'),
        ),
    ]
