# Generated by Django 5.1.7 on 2026-04-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta_de_operacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetadeoperacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=8),
        ),
    ]
