# Generated by Django 5.1.7 on 2026-04-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjeta_de_operacion', '0003_alter_tarjetadeoperacion_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetadeoperacion',
            name='estado',
            field=models.CharField(choices=[('p', 'PENDIENTE'), ('e', 'EMITIDA'), ('v', 'VENCIDA')], default='p', max_length=1),
        ),
    ]
