# Generated by Django 5.1.7 on 2026-03-30 17:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite_file', models.FileField(blank=True, null=True, upload_to='tramites/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('reporte_file', models.FileField(blank=True, null=True, upload_to='reportes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('numero_tramite', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='N° de Trámite')),
                ('estado_deposito', models.BooleanField(default=False)),
                ('tipo_tramite', models.CharField(choices=[('otorgacion', 'Otorgación Nueva de Tarjetas de Operación'), ('renovacion', 'Renovación de Tarjetas de Operación')], default='otorgacion', max_length=20)),
                ('estado_tramite', models.CharField(choices=[('pendiente', 'Tramite Pendiente'), ('validado', 'Tramite Validado'), ('observado', 'Tramite Observado')], default='pendiente', max_length=20)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_observacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_deposito', models.CharField(max_length=50, unique=True)),
                ('monto_deposito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_deposito', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposito', to='tramite.tramite')),
            ],
        ),
    ]
