# Generated by Django 5.1.7 on 2026-04-23 14:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('o', 'Otorgación Nueva de Tarjetas de Operación'), ('r', 'Renovación de Tarjetas de Operación')], max_length=1)),
                ('estado', models.CharField(choices=[('p', 'PENDIENTE'), ('v', 'VALIDO'), ('o', 'OBSERVADO')], default='p', max_length=1)),
                ('licencia', models.CharField(choices=[('l1', 'InterProvincial'), ('l2', 'Interprov.ATL'), ('l3', 'Interprov.Confederado'), ('l4', 'Interprov.Confe.SCZ'), ('l5', 'Interprov.Cooperativas')], max_length=2)),
                ('informe_tecnico', models.FileField(blank=True, null=True, upload_to='informes_tecnicos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('informe_legal', models.FileField(blank=True, null=True, upload_to='informes_legales/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('resolucion_administrativa', models.FileField(blank=True, null=True, upload_to='resolucion_administrativa/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('deposito', models.BooleanField(default=False)),
                ('fojas', models.PositiveIntegerField(blank=True, null=True)),
                ('rutas', models.TextField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramite_operador', to='operador.operador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramite_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_deposito', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposito_tramite', to='tramite.tramite')),
            ],
        ),
    ]
