# Generated by Django 5.1.7 on 2026-04-15 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operador', '0001_initial'),
        ('tramite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas_de_operacion', to='operador.operador'),
        ),
    ]
