# Generated by Django 5.1.7 on 2026-04-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='area_firma_1',
            field=models.CharField(blank=True, default='SECRETARIO DEPARTAMENTAL DE JURÍDICA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='area_firma_2',
            field=models.CharField(blank=True, default='SECRETARIO DEPARTAMENTAL DE COORDINACIÓN GENERAL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='banco',
            field=models.CharField(blank=True, default='BANCO UNION', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='cuenta',
            field=models.CharField(blank=True, default='1-6024553', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='encargado_firma_1',
            field=models.CharField(blank=True, default='Abog. Heber Rodriguez Flores', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='encargado_firma_2',
            field=models.CharField(blank=True, default='Oscar Mendoza Mamani', max_length=100, null=True),
        ),
    ]
