# Generated by Django 5.1.7 on 2026-04-05 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='numero_tramite',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.CharField(choices=[('otorgacion', 'Otorgación Nueva de Tarjetas de Operación'), ('renovacion', 'Renovación de Tarjetas de Operación')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
