# Generated by Django 5.1.7 on 2026-05-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_tramite_area_firma_1_tramite_area_firma_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='segunda_revicion',
            field=models.CharField(choices=[('p', 'PENDIENTE'), ('v', 'VALIDO'), ('o', 'OBSERVADO')], default='p', max_length=1),
        ),
    ]
