# Generated by Django 5.1.7 on 2026-04-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('sa', 'Super Administrador'), ('a', 'Administrador'), ('u', 'Tecnico')], default='u', max_length=2),
        ),
    ]
