# Generated by Django 5.1.7 on 2026-04-13 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Ingreso al sistema'), ('LOGOUT', 'Salida del sistema'), ('CREAR', 'Creación de registro'), ('EDITAR', 'Edición de registro'), ('ELIMINAR', 'Eliminación de registro'), ('IMPRIMIR', 'Impresión de documento'), ('OTRO', 'Otra acción')], max_length=20)),
                ('descripcion', models.TextField()),
                ('modelo_afectado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_registro', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Acción',
                'verbose_name_plural': 'Historial de Acciones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
