# Generated by Django 5.1.7 on 2026-04-05 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transporte', models.CharField(choices=[('pasajeros', 'PASAJEROS'), ('carga', 'CARGA')], default='pasajeros', max_length=20)),
                ('modelo', models.PositiveIntegerField()),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('chasis', models.CharField(max_length=100, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='vehiculo.colorvehiculo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='vehiculo.marcavehiculo')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='afiliado.afiliado')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='vehiculo.tipovehiculo')),
            ],
        ),
    ]
