# Generated by Django 5.1.7 on 2026-04-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(blank=True, max_length=500)),
                ('transporte', models.CharField(choices=[('p', 'PASAJEROS'), ('c', 'CARGA')], max_length=20)),
                ('modelo', models.PositiveIntegerField()),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('chasis', models.CharField(max_length=100, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculo_afiliado', to='afiliado.afiliado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculo_marca', to='vehiculo.marcavehiculo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculo_tipo', to='vehiculo.tipovehiculo')),
            ],
        ),
    ]
