# Generated by Django 5.1.7 on 2026-06-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad',
            field=models.CharField(max_length=20),
        ),
    ]
